ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
        dtbo-$(CONFIG_ARCH_KONA) += \
                oneplus8p-overlay-evb.dtbo \
                oneplus8p-overlay-t0.dtbo \
                oneplus8p-overlay-evt1.dtbo \
                oneplus8p-overlay-dvt.dtbo \
                oneplus8-overlay-t0.dtbo \
                oneplus8-overlay-evt1.dtbo \
                oneplus8-overlay-dvt.dtbo \
                oneplus8v-overlay-t0.dtbo \
                oneplus8v-overlay-evt1.dtbo \
                oneplus8v-overlay-dvt.dtbo

oneplus8p-overlay-evb.dtbo-base := qcom/kona.dtb qcom/kona-v2.dtb qcom/kona-v2.1.dtb
oneplus8p-overlay-t0.dtbo-base := qcom/kona.dtb qcom/kona-v2.dtb qcom/kona-v2.1.dtb
oneplus8p-overlay-evt1.dtbo-base := qcom/kona.dtb qcom/kona-v2.dtb qcom/kona-v2.1.dtb
oneplus8p-overlay-dvt.dtbo-base := qcom/kona.dtb qcom/kona-v2.dtb qcom/kona-v2.1.dtb

oneplus8-overlay-t0.dtbo-base := qcom/kona.dtb qcom/kona-v2.dtb qcom/kona-v2.1.dtb
oneplus8-overlay-evt1.dtbo-base := qcom/kona.dtb qcom/kona-v2.dtb qcom/kona-v2.1.dtb
oneplus8-overlay-dvt.dtbo-base := qcom/kona.dtb qcom/kona-v2.dtb qcom/kona-v2.1.dtb

oneplus8v-overlay-t0.dtbo-base := qcom/kona.dtb qcom/kona-v2.dtb qcom/kona-v2.1.dtb
oneplus8v-overlay-evt1.dtbo-base := qcom/kona.dtb qcom/kona-v2.dtb qcom/kona-v2.1.dtb
oneplus8v-overlay-dvt.dtbo-base := qcom/kona.dtb qcom/kona-v2.dtb qcom/kona-v2.1.dtb
endif
